version: '3.5'

services:
    mongo-db:
        image: mongo
        container_name: mongo-db
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
        volumes:
            - ~/ws/answer-machine-backend-volume:/data/db
        networks:
            - mongo
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongo-db
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo-db:27017/
        networks:
            - mongo
networks:
    mongo: